### ISSUE TITLE
can this plugin have some offset to the documenet top?

### ISSUE THREAD

**Issue by kakaluote444** [tscanlin/tocbot#161]
the default event is that the article heading will position to top when i click the outline.how can i make it with some margin to the top document.(sorry my pool english...)
![image](https://user-images.githubusercontent.com/15668875/69040863-86d0f700-0a29-11ea-86de-b47bc0eae414.png)

**Comment by tscanlin** [comment]
Yes that’s possible, Please see this section of the readme: https://github.com/tscanlin/tocbot/blob/master/README.md#fixed-headers

**Comment by kakaluote444** [comment]
i think it will help more people To solve this FAQ if you could give a online example
(i have focused on the project for a long time,very like this table content plugin style,It is highly recommended you add this example on your website or in the other way.)

**Comment by kakaluote444** [comment]
haha.this problem fixed by myself.
![image](https://user-images.githubusercontent.com/15668875/69481022-3a7e2080-0e48-11ea-8fb4-780a1be04385.png)

**Comment by tscanlin** [comment]
Glad you were able to fix this issue yourself. One reason that I don't advocate for the JS solution you suggested is that it doesn't always handle the case where you load the url with the hash and go there directly instead of clicking toc links. You could solve that with another JS event that adjusts scroll on load but I'd imagine it may flicker. Anyway, glad you found a solution that worked for you.

**Comment by kakaluote444** [comment]
can we choose js function(animate or window.scrollTop) instead of anchor default action?what do you think of the suggestion that flicker problem may disappear.and you can easily control the header position to scroll where you want to navigate.

**Comment by tscanlin** [comment]
The onClick option can already be used to customize animation as you did. Do you have an example site somewhere to see if flicker is still an issue?

**Comment by kamranayub** [comment]
FWIW I think there may be an issue introduced after this issue was closed in later Chrome versions because that CSS snippet doesn't address it anymore if it used to. I'm basing this off the Ghost tutorial: https://ghost.org/tutorials/adding-a-table-of-contents/
